apiVersion: v1
kind: Secret
metadata:
  name: goodfood-secrets
  namespace: goodfood
type: Opaque
stringData:
  mysql-root-password: ""
  # If you keep a confidential config repo:
  # config-server-git-username: ""
  # config-server-git-password: ""
