server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Shubh-Namdev/goodfood-config-repo
          default-label: main
          clone-on-start: true
  profiles:
    active: native

management:
  endpoints:
    web:
      exposure:
        include: "*"