server:
  port: 8090

spring:
  application:
    name: goodfood-gateway

  config:
    import: configserver:http://localhost:8888

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9000
          predicates:
            - Path=/auth/**,/oauth2/**,/actuator/**
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: http://localhost:8083
          predicates:
            - Path=/payments/**
        - id: restaurant-service
          uri: http://localhost:8084
          predicates:
            - Path=/restaurants/**
        - id: delivery-service
          uri: http://localhost:8085
          predicates:
            - Path=/deliveries/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
