apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: goodfood
spec:
  serviceName: kafka
  replicas: 1
  selector: { matchLabels: { app: kafka } }
  template:
    metadata: { labels: { app: kafka } }
    spec:
      containers:
        - name: kafka
          image: apache/kafka:latest
          ports:
            - { containerPort: 9092, name: broker }
            - { containerPort: 9093, name: controller }
          env:
            - { name: KAFKA_NODE_ID, value: "1" }
            - { name: KAFKA_PROCESS_ROLES, value: "broker,controller" }
            - { name: KAFKA_LISTENERS, value: "PLAINTEXT://:9092,CONTROLLER://:9093" }
            - { name: KAFKA_ADVERTISED_LISTENERS, value: "PLAINTEXT://kafka-0.kafka.goodfood.svc.cluster.local:9092" }
            - { name: KAFKA_CONTROLLER_LISTENER_NAMES, value: "CONTROLLER" }
            - { name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP, value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT" }
            - { name: KAFKA_CONTROLLER_QUORUM_VOTERS, value: "1@kafka-0.kafka.goodfood.svc.cluster.local:9093" }
          volumeMounts:
            - { name: data, mountPath: /var/lib/kafka/data }
          readinessProbe:
            tcpSocket: { port: 9092 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket: { port: 9092 }
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests: { cpu: "300m", memory: "512Mi" }
            limits:   { cpu: "1",    memory: "1.5Gi" }
  volumeClaimTemplates:
    - metadata: { name: data }
      spec:
        accessModes: ["ReadWriteOnce"]
        resources: { requests: { storage: 10Gi } }
