spring:
  datasource:
    url: jdbc:mysql://mysql.goodfood.svc.cluster.local:3306/goodfood_authdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

  kafka:
    bootstrap-servers: kafka.goodfood.svc.cluster.local:9092
